### ISSUE TITLE
is it possible to add an option to unmount a mounted zip file system?

### ISSUE THREAD

**Issue by donaldtone** [TomasHubelbauer/vscode-zip-file-system#2]
it will be better to give user more flexibility.

**Comment by TomasHubelbauer** [comment]
For  sure, I will add it ASAP.

**Comment by TomasHubelbauer** [comment]
Hey, sorry to get back to you over a year later, so much for an "ASAP", huh!

You can remove the mounted file system by simply removing it from the workspace using its context menu. That will do the same thing I would do in the code should I implement this as a command.

Hope this helps, let me know if there's more I can do to make your life using this extension easier and I promise I will get to it faster this time around. :-) Have a great day!
